---
title: "Systematic Review Extraction Script Template"
date: "13 dec 2018 at 14:33:34"
output:
  html_document:
    self-contained: yes
    toc: false
params:
  rxsVersion = "0.1.0"
---

```{r rxsChunk-setup, include=FALSE, messages=FALSE}
### First load (and perhaps install) userfriendlyscience
if (!require('userfriendlyscience')) {
  install.packages('userfriendlyscience');
  require('userfriendlyscience');
}

### Other packages
safeRequire('ufs');              ### To flatten vectors with VecTxtQ in metabefor
safeRequire('googlesheets');     ### To import data from google sheets in metabefor
safeRequire('jsonlite');         ### To import a list of country codes in metabefor
safeRequire('data.tree');        ### To work with data structured in a tree in metabefor
safeRequire('pander');           ### To print the dataframe with results in a nice way
safeRequire('devtools');         ### To install metabefor from github repo
                                 ### ... Which we then do here:
devtools::install_github('Matherion/metabefor',
                         quiet=TRUE);
require('metabefor');            ### ... After which we load it

### Settings
knitr::opts_chunk$set(echo = FALSE);             ### Suppress R command printing
knitr::opts_chunk$set(comment=NA);               ### Suppress output prefix
pander::panderOptions('table.split.table', Inf); ### Disable table splitting
```

```{r rxsChunk-fieldnames}
eC <- list(titleCol="title",
           descriptionCol="description",
           identifierCol="identifier",
           valueTemplateCol="valueTemplate",
           validValuesCol="validValues",
           defaultCol="default",
           parentCol="parent",
           entityRefCol="entityRef",
           fieldRefCol="fieldRef",
           ownerCol="owner",
           listCol="list",
           collapsingCol="collapsing",
           repeatingCol="repeating",
           recurringCol="recurring",
           recursingCol="recursing",
           identifyingCol="identifying");

valueTemplateCols <- list(identifierCol="identifier",
                          descriptionCol="description",
                          validValuesCol="validValues",
                          defaultCol="default",
                          examplesCol="examples",
                          validationCol="validation",
                          errorCol="error");
```

```{r rxsChunk, echo=FALSE}
################################################################################
######################################################## START: study (ROOT) ###
################################################################################
study <- Node$new('study');
################################################################################

  ##############################################################################
  ########################################################### START: studyId ###
  ##############################################################################
  study$AddChild('studyId');
  study$studyId[['value']] <-
  ##############################################################################
  ### 
  ### STUDY IDENTIFIER
  ### 
  ### Unique identifier for this study
  ### 
  ##############################################################################
      
      "enter xdoi here"
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### For studies with a DOI, "doi:" directly followed by the DOI; for
  ### studies without a DOI, the DOI prefix of the publisher (see
  ### https://gist.github.com/TomDemeranville/8699224), followed by a
  ### slash, followed by the ISSN, followed by a dash, followed by the
  ### year of publication, followed by a dash, followed by the starting
  ### page. If no DOI prefix can be located, instead use 'NA'.
  ### 
  ### EXAMPLES:
  ### 
  ### "doi:10.18637/jss.v036.i03"
  ### "nodoi:10.1111/0965-2140/2003-951"
  ### "doi:10.1136/bmj.2.2288.1243"
  ### 
  ##############################################################################
  study$studyId[['validation']] <- expression(nchar(VALUE)>10);
  ##############################################################################
  ############################################################# END: studyId ###
  ##############################################################################


  ##############################################################################
  ########################################################## START: comments ###
  ##############################################################################
  study$AddChild('comments');
  study$comments[['value']] <-
  ##############################################################################
  ### 
  ### GENERAL COMMENTS
  ### 
  ### Any general comments the coder wants to add about this study
  ### 
  ##############################################################################
      
      ""
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### A single character value
  ### 
  ### EXAMPLES:
  ### 
  ### "example"
  ### "another example"
  ### 
  ##############################################################################
  study$comments[['validation']] <- expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1));
  ##############################################################################
  ############################################################ END: comments ###
  ##############################################################################


  ##############################################################################
  ##################################################### START: yearPublished ###
  ##############################################################################
  study$AddChild('yearPublished');
  study$yearPublished[['value']] <-
  ##############################################################################
  ### 
  ### YEAR OF PUBLICATION
  ### 
  ### Year article was published
  ### 
  ##############################################################################
      
      NA
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### One year
  ### 
  ### EXAMPLES:
  ### 
  ### 2001
  ### 2002
  ### 1987
  ### 
  ##############################################################################
  study$yearPublished[['validation']] <- expression((is.numeric(VALUE) && (nchar(VALUE)==4)));
  ##############################################################################
  ####################################################### END: yearPublished ###
  ##############################################################################


  ##############################################################################
  ########################################################### START: country ###
  ##############################################################################
  study$AddChild('country');
  study$country[['value']] <-
  ##############################################################################
  ### 
  ### COUNTRY
  ### 
  ### Country (or countries) where the data were collected
  ### 
  ##############################################################################
      
      NA
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### A character vector of the ISO 3166-1 alpha-2 country code(s)
  ### 
  ### EXAMPLES:
  ### 
  ### "NL"
  ### c("NL", "BE")
  ### 
  ##############################################################################
  study$country[['validation']] <- expression(is.na(VALUE) || (VALUE %in% countryCodeList()));
  ##############################################################################
  ############################################################# END: country ###
  ##############################################################################


  ##############################################################################
  ########################################################### START: methods ###
  ##############################################################################
  study$AddChild('methods');
  ##############################################################################
  ### 
  ### METHODS
  ### 
  ### Description of the methods used by the study
  ### 
  ##############################################################################
      
  
    ############################################################################
    ############################################################### START: N ###
    ############################################################################
    study$methods$AddChild('N');
    study$methods$N[['value']] <-
    ############################################################################
    ### 
    ### SAMPLE SIZE
    ### 
    ### Total number of human participants in the study (note: the
    ### actual sample size may be larger if multiple observations are
    ### collected per participant)
    ### 
    ############################################################################
        
        NA
        
    ############################################################################
    ######################################### VALUE DESCRIPTION AND EXAMPLES ###
    ############################################################################
    ### 
    ### Any valid whole number
    ### 
    ### EXAMPLES:
    ### 
    ### 30
    ### 8762
    ### 
    ############################################################################
    study$methods$N[['validation']] <- expression(is.na(VALUE) || (is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1)));
    ############################################################################
    ################################################################# END: N ###
    ############################################################################
  
      
  ##############################################################################
  ############################################################# END: methods ###
  ##############################################################################


  ##############################################################################
  ######################################################## START: logicModel ###
  ##############################################################################
  study$AddChild('logicModel');
  ##############################################################################
  ### 
  ### LOGIC MODEL
  ### 
  ### Description of the main elements in the intervention logic model
  ### (i.e. the logic model of the problem and the logic model of change)
  ### 
  ##############################################################################
      
  
    ############################################################################
    ############################################### START: descr.targetGroup ###
    ############################################################################
    study$logicModel$AddChild('descr.targetGroup');
    study$logicModel$descr.targetGroup[['value']] <-
    ############################################################################
    ### 
    ### TARGET GROUP(S)
    ### 
    ### Description of the target group(s) of the intervention
    ### 
    ############################################################################
        
        ""
        
    ############################################################################
    ######################################### VALUE DESCRIPTION AND EXAMPLES ###
    ############################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ############################################################################
    study$logicModel$descr.targetGroup[['validation']] <- expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1));
    ############################################################################
    ################################################# END: descr.targetGroup ###
    ############################################################################
  
  
    ############################################################################
    ############################################## START: descr.determinants ###
    ############################################################################
    study$logicModel$AddChild('descr.determinants');
    study$logicModel$descr.determinants[['value']] <-
    ############################################################################
    ### 
    ### DETERMINANT(S)
    ### 
    ### Description of the determinant(s) the intervention targets
    ### 
    ############################################################################
        
        ""
        
    ############################################################################
    ######################################### VALUE DESCRIPTION AND EXAMPLES ###
    ############################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ############################################################################
    study$logicModel$descr.determinants[['validation']] <- expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1));
    ############################################################################
    ################################################ END: descr.determinants ###
    ############################################################################
  
  
    ############################################################################
    ################################################### START: descr.problem ###
    ############################################################################
    study$logicModel$AddChild('descr.problem');
    study$logicModel$descr.problem[['value']] <-
    ############################################################################
    ### 
    ### PROBLEM
    ### 
    ### Description of the problem and the background of the problem
    ### 
    ############################################################################
        
        ""
        
    ############################################################################
    ######################################### VALUE DESCRIPTION AND EXAMPLES ###
    ############################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ############################################################################
    study$logicModel$descr.problem[['validation']] <- expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1));
    ############################################################################
    ##################################################### END: descr.problem ###
    ############################################################################
  
  
    ############################################################################
    ################################################### START: descr.methods ###
    ############################################################################
    study$logicModel$AddChild('descr.methods');
    study$logicModel$descr.methods[['value']] <-
    ############################################################################
    ### 
    ### METHOD(S)
    ### 
    ### Description of the method(s) employed to target the
    ### determinant(s)
    ### 
    ############################################################################
        
        ""
        
    ############################################################################
    ######################################### VALUE DESCRIPTION AND EXAMPLES ###
    ############################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ############################################################################
    study$logicModel$descr.methods[['validation']] <- expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1));
    ############################################################################
    ##################################################### END: descr.methods ###
    ############################################################################
  
  
    ############################################################################
    ############################################## START: descr.applications ###
    ############################################################################
    study$logicModel$AddChild('descr.applications');
    study$logicModel$descr.applications[['value']] <-
    ############################################################################
    ### 
    ### APPLICATION(S)
    ### 
    ### Description of the application(s) in which the method(s) are
    ### implemented
    ### 
    ############################################################################
        
        ""
        
    ############################################################################
    ######################################### VALUE DESCRIPTION AND EXAMPLES ###
    ############################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ############################################################################
    study$logicModel$descr.applications[['validation']] <- expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1));
    ############################################################################
    ################################################ END: descr.applications ###
    ############################################################################
  
      
  ##############################################################################
  ########################################################## END: logicModel ###
  ##############################################################################

    
################################################################################
########################################################## END: study (ROOT) ###
################################################################################
class(study) <- c('rxs', class(study));
```


```{r rxsChunk-show-extracted-data, results='asis'}
print.rxs(study);
```

```{r rxsChunk-validation, results='asis'}
rxs_validation(study);
pandoc.header('Validation results', level=1)
#rxs_validation(study,
#               rxsStructure = fullResults$rxsStructure);
if (length(study$validationResults) > 2) {
  cat(paste0('- ', study$validationResults), sep='
');
} else {
  cat('Validation successful!');
}
```

